# -*- coding: utf-8 -*-
"""dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jp5gK1iz4oDEPw5rssCTooZYdj--iQL
"""

import pandas as pd
import numpy as np

data = {
'Ismlar': ['Ozod', 'Asad', 'Xasan'],
'Yosh': [15, 16, 17]
}
df = pd.DataFrame(data)
print(df)

df.to_excel('data1234.xlsx')